[display]
compact = false
use_pager = false

[style.description]
foreground = "yellow"

[style.command_name]
foreground = "red"
bold = true

[style.example_text]
foreground = "green"

[style.example_code]
foreground = "white"

[style.example_variable]
foreground = "blue"

[updates]
auto_update = true
auto_update_interval_hours = 24
