#!/bin/sh
CHOICE=$(printf '%s\n' "Start" "Stop" | rofi -dmenu -p 'VPN Menu' -theme Arc-Dark -icon-theme "Papirus" -show-icons -terminal alacritty -font 'DejaVu Sans Mono 20')
case $CHOICE in
    Start) (cd ~/.config/vpn/ && sudo openvpn doma_all.conf) ;;
    Stop) sudo pkill openvpn ;;
esac

