#!/bin/sh
CHOICE=$(printf '%s\n' "Battery" "Auto" "AC" | rofi -dmenu -p 'Power Menu' -theme Arc-Dark -icon-theme "Papirus" -show-icons -terminal alacritty -font 'DejaVu Sans Mono 20')
case $CHOICE in
    "Battery") sudo tlp bat ;;
    "Auto") sudo tlp start ;;
    "AC") sudo tlp ac ;;
esac
