#!/bin/sh
CHOICE=$(printf '%s\n' "Performance" "Balanced" "Power-saver" | rofi -dmenu -p 'Power Menu' -theme Arc-Dark -icon-theme "Papirus" -show-icons -terminal alacritty -font 'DejaVu Sans Mono 20')
case $CHOICE in
    "Performance") sudo tlp performance ;;
    "Balanced") sudo tlp balanced ;;
    "Power-saver") sudo tlp power-saver ;;
esac
